//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CONGTHUC
    {
        [DisplayName("Mã món")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Mon_ID { get; set; }
        [DisplayName("Mã nguyên liệu")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string NguyenLieu_ID { get; set; }
        [DisplayName("Số lượng nguyên liệu cần")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Vui lòng chỉ nhập số hoặc số thập phân")]
        public Nullable<decimal> SoLuongNLCan { get; set; }
    
        public virtual MON MON { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
