//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FEEDBACK
    {
        public string Feedback_ID { get; set; }
        [DisplayName("Họ tên khách hàng")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string HoTen { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Email { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        [DisplayName("Nội dung")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [StringLength(200, MinimumLength = 8, ErrorMessage = "{0} có độ dài bắt buộc từ {2} tới {1} ký tự")]
        public string NoiDung { get; set; }
    }
}
