//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string KhachHang_ID { get; set; }
        [DisplayName("Họ tên khách hàng")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string HoTen { get; set; }
        [DisplayName("Số điện thoại khách hàng")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string SDTKH { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Email { get; set; }
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string UserName { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string PassWord { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string DiaChi { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
