//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.MONs = new HashSet<MON>();
        }
        public string KhuyenMai_ID { get; set; }
        [DisplayName("Tên khuyến mãi")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string TenKhuyenMai { get; set; }
        [DisplayName("Phần trăm khuyến mãi")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Vui lòng vào chỉ duy nhất số")]
        public Nullable<double> PhanTramKhuyenMai { get; set; }
        [DisplayName("Ngày bắt đầu")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [DisplayName("Ngày kết thúc")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MON> MONs { get; set; }
        [NotMapped]
        public List<KHUYENMAI> ListKM { get; set; }
    }
}
