//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class MON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON()
        {
            AnhMon = "~/Images/add.png";
            this.CONGTHUCs = new HashSet<CONGTHUC>();
            this.CTDONHANGs = new HashSet<CTDONHANG>();
        }
        
        public List<MON> ListMon { get; set; }

        public string Mon_ID { get; set; }
        [DisplayName("Tên món")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string TenMon { get; set; }
        [DisplayName("Loại món")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Loai_ID { get; set; }
        [DisplayName("Size món")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Size_ID { get; set; }
        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string DonVi_ID { get; set; }
        [DisplayName("Ảnh minh họa")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string AnhMon { get; set; }
        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Đơn giá phải là số")]
        public Nullable<decimal> DonGia { get; set; }
        public string KhuyenMai_ID { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTHUC> CONGTHUCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
