//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUYENLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEU()
        {
            this.CONGTHUCs = new HashSet<CONGTHUC>();
        }
    
        public string NguyenLieu_ID { get; set; }
        [DisplayName("Tên nhà cung cấp")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string NCC_ID { get; set; }
        [StringLength(50, MinimumLength = 2, ErrorMessage = "{0} có độ dài bắt buộc từ {2} tới {1} ký tự")]
        [DisplayName("Tên nguyên liệu")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string TenNguyenLieu { get; set; }
        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string DonVi_ID { get; set; }
        [DisplayName("Số lượng tồn")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Vui lòng chỉ nhập số hoặc số thập phân")]
        public Nullable<decimal> SoLuongTon { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTHUC> CONGTHUCs { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public List<NGUYENLIEU> ListNL { get; set; }
    }
}
