//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NHACUNGCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHACUNGCAP()
        {
            this.NGUYENLIEUx = new HashSet<NGUYENLIEU>();
        }
    
        public string NCC_ID { get; set; }
        [DisplayName("Tên nhà cung cấp")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
       // [RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$",ErrorMessage = "Vui lòng chỉ nhập chữ và số")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "{0} có độ dài bắt buộc từ {2} tới {1} ký tự")]
        public string TenNCC { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        [StringLength(100, MinimumLength = 8, ErrorMessage = "{0} có độ dài bắt buộc từ {2} tới {1} ký tự")]
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUYENLIEU> NGUYENLIEUx { get; set; }
        public List<NHACUNGCAP> ListNCC { get; set; }
    }
}
