//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHTFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }
    
        public string NhanVien_ID { get; set; }
        [DisplayName("Họ tên nhân viên")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string HoTenNV { get; set; }
        [DisplayName("Tên tài khoản")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string UserName { get; set; }
        [DisplayName("Mật khảu")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string PassWord { get; set; }
        [DisplayName("Quyền truy cập")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Quyen_ID { get; set; }
        [DisplayName("Ngày sinh")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string DiaChi { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string SDT { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "{0} là bắt buộc")]
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual QUYENTRUYCAP QUYENTRUYCAP { get; set; }
    }
}
